const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const ts = require('typescript');
const exports_ = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('apps/desktop/src/main/data-profile.ts','utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:exports_,require});
const root=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'fern-profile-test-'));
const branded=path.join(root,'Fern'), legacy=path.join(root,'Iris OpenVINO Studio');
assert.equal(exports_.resolveDataProfile(root),branded);
fs.mkdirSync(legacy); assert.equal(exports_.resolveDataProfile(root),legacy);
fs.mkdirSync(branded); fs.mkdirSync(path.join(legacy,'studio-data','outputs'),{recursive:true});
fs.writeFileSync(path.join(legacy,'studio-data','outputs','old.png'),'fixture');
assert.equal(exports_.resolveDataProfile(root),legacy);
fs.mkdirSync(path.join(branded,'studio-data','outputs'),{recursive:true});
fs.writeFileSync(path.join(branded,'studio-data','outputs','new.png'),'fixture');
assert.equal(exports_.resolveDataProfile(root),branded);
const custom=path.join(root,'custom');fs.mkdirSync(custom);
fs.writeFileSync(path.join(legacy,'iris-studio.json'),JSON.stringify({projectRoot:custom}));
assert.equal(exports_.savedDataRoot(legacy),custom);
fs.writeFileSync(path.join(legacy,'iris-studio.json'),'{broken');
assert.equal(exports_.savedDataRoot(legacy),null);
fs.rmSync(root,{recursive:true,force:true});
console.log('Profile selection and saved root tests passed');
